--------------------------------------------------------
--  File created - Tuesday-August-27-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CAR_OWNER_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "AVILCHENKO"."CAR_OWNER_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CAR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVILCHENKO"."CAR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SERVICE_CAR_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "AVILCHENKO"."SERVICE_CAR_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SERVICE_DETAIL_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "AVILCHENKO"."SERVICE_DETAIL_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SERVICE_STATUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVILCHENKO"."SERVICE_STATUS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  File created - Tuesday-August-27-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAR
--------------------------------------------------------

  CREATE TABLE "AVILCHENKO"."CAR" 
   (	"CAR_ID" NUMBER, 
	"BRAND" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"VIN" VARCHAR2(30 BYTE), 
	"CAR_OWNER_ID" NUMBER(5,0), 
	"PLATE_NUMBER" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Table CAR_OWNER
--------------------------------------------------------

  CREATE TABLE "AVILCHENKO"."CAR_OWNER" 
   (	"CAR_OWNER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(40 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"MIDDLE_NAME" VARCHAR2(40 BYTE), 
	"OWNER_ADDRESS_STREET" VARCHAR2(50 BYTE), 
	"OWNER_ADDRESS_CITY" VARCHAR2(30 BYTE), 
	"OWNER_ADDRESS_ZIP_CODE" NUMBER(5,0), 
	"OWNER_PHONE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Table SERVICE_CAR
--------------------------------------------------------

  CREATE TABLE "AVILCHENKO"."SERVICE_CAR" 
   (	"SERVICE_CAR_ID" NUMBER, 
	"START_SERVICE" DATE, 
	"END_SERVICE" DATE, 
	"SERVICE_DESCRIPTION" VARCHAR2(50 BYTE), 
	"CAR_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Table SERVICE_DETAIL
--------------------------------------------------------

  CREATE TABLE "AVILCHENKO"."SERVICE_DETAIL" 
   (	"SERVICE_DETAIL_ID" NUMBER(5,0), 
	"SERVICE_CAR_ID" NUMBER(5,0), 
	"ITEM_COST" FLOAT(126), 
	"ITEM_DESC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Table SERVICE_STATUS
--------------------------------------------------------

  CREATE TABLE "AVILCHENKO"."SERVICE_STATUS" 
   (	"SERVICE_STATUS_ID" NUMBER(5,0), 
	"SERVICE_CAR_ID" NUMBER(5,0), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"SERVICE_STATUS_TYPE_ID" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Table SERVICE_STATUS_TYPE
--------------------------------------------------------

  CREATE TABLE "AVILCHENKO"."SERVICE_STATUS_TYPE" 
   (	"SERVICE_STATUS_TYPE_ID" NUMBER, 
	"SERVICE_STATUS_DESC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index CAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."CAR_PK" ON "AVILCHENKO"."CAR" ("CAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index CAR_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."CAR_UK1" ON "AVILCHENKO"."CAR" ("VIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index CAR_PLATE_NUMNER_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."CAR_PLATE_NUMNER_UK2" ON "AVILCHENKO"."CAR" ("PLATE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index CAR_OWNER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."CAR_OWNER_PK" ON "AVILCHENKO"."CAR_OWNER" ("CAR_OWNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index CAR_OWNER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."CAR_OWNER_UK1" ON "AVILCHENKO"."CAR_OWNER" ("OWNER_PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index SERVICE_CAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."SERVICE_CAR_PK" ON "AVILCHENKO"."SERVICE_CAR" ("SERVICE_CAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index SERVICE_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."SERVICE_DETAIL_PK" ON "AVILCHENKO"."SERVICE_DETAIL" ("SERVICE_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index SERVICE_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."SERVICE_STATUS_PK" ON "AVILCHENKO"."SERVICE_STATUS" ("SERVICE_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index SERVICE_STATUS_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVILCHENKO"."SERVICE_STATUS_TYPE_PK" ON "AVILCHENKO"."SERVICE_STATUS_TYPE" ("SERVICE_STATUS_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Trigger CAR_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AVILCHENKO"."CAR_TRG" 
BEFORE INSERT ON CAR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CAR_ID IS NULL THEN
      SELECT CAR_SEQ.NEXTVAL INTO :NEW.CAR_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVILCHENKO"."CAR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CAR_OWNER_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AVILCHENKO"."CAR_OWNER_TRG2" 
BEFORE INSERT ON CAR_OWNER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CAR_OWNER_ID IS NULL THEN
      SELECT CAR_OWNER_SEQ2.NEXTVAL INTO :NEW.CAR_OWNER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVILCHENKO"."CAR_OWNER_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICE_CAR_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AVILCHENKO"."SERVICE_CAR_TRG2" 
BEFORE INSERT ON SERVICE_CAR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SERVICE_CAR_ID IS NULL THEN
      SELECT SERVICE_CAR_SEQ2.NEXTVAL INTO :NEW.SERVICE_CAR_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVILCHENKO"."SERVICE_CAR_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICE_DETAIL_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AVILCHENKO"."SERVICE_DETAIL_TRG2" 
BEFORE INSERT ON SERVICE_DETAIL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SERVICE_DETAIL_ID IS NULL THEN
      SELECT SERVICE_DETAIL_SEQ2.NEXTVAL INTO :NEW.SERVICE_DETAIL_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVILCHENKO"."SERVICE_DETAIL_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICE_STATUS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AVILCHENKO"."SERVICE_STATUS_TRG" 
BEFORE INSERT ON SERVICE_STATUS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SERVICE_STATUS_ID IS NULL THEN
      SELECT SERVICE_STATUS_SEQ.NEXTVAL INTO :NEW.SERVICE_STATUS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVILCHENKO"."SERVICE_STATUS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CAR
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."CAR" MODIFY ("PLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR" ADD CONSTRAINT "CAR_VIN_UK1" UNIQUE ("VIN")
  USING INDEX (CREATE UNIQUE INDEX "AVILCHENKO"."CAR_UK1" ON "AVILCHENKO"."CAR" ("VIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE" )  ENABLE;
  ALTER TABLE "AVILCHENKO"."CAR" ADD CONSTRAINT "CAR_PLATE_NUMNER_UK2" UNIQUE ("PLATE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE"  ENABLE;
  ALTER TABLE "AVILCHENKO"."CAR" MODIFY ("CAR_ID" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR" MODIFY ("BRAND" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR" MODIFY ("VIN" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR" ADD CONSTRAINT "CAR_PK" PRIMARY KEY ("CAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE"  ENABLE;
  ALTER TABLE "AVILCHENKO"."CAR" MODIFY ("CAR_OWNER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAR_OWNER
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."CAR_OWNER" ADD CONSTRAINT "CAR_OWNER_UK1" UNIQUE ("OWNER_PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE"  ENABLE;
  ALTER TABLE "AVILCHENKO"."CAR_OWNER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR_OWNER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR_OWNER" MODIFY ("OWNER_ADDRESS_STREET" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR_OWNER" MODIFY ("OWNER_ADDRESS_CITY" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR_OWNER" MODIFY ("OWNER_ADDRESS_ZIP_CODE" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR_OWNER" MODIFY ("OWNER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR_OWNER" MODIFY ("CAR_OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."CAR_OWNER" ADD CONSTRAINT "CAR_OWNER_PK" PRIMARY KEY ("CAR_OWNER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICE_CAR
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."SERVICE_CAR" MODIFY ("SERVICE_CAR_ID" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_CAR" MODIFY ("START_SERVICE" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_CAR" MODIFY ("SERVICE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_CAR" ADD CONSTRAINT "SERVICE_CAR_PK" PRIMARY KEY ("SERVICE_CAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE"  ENABLE;
  ALTER TABLE "AVILCHENKO"."SERVICE_CAR" MODIFY ("END_SERVICE" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_CAR" MODIFY ("CAR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_DETAIL
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."SERVICE_DETAIL" ADD CONSTRAINT "SERVICE_DETAIL_PK" PRIMARY KEY ("SERVICE_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE"  ENABLE;
  ALTER TABLE "AVILCHENKO"."SERVICE_DETAIL" MODIFY ("ITEM_COST" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_DETAIL" MODIFY ("SERVICE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_DETAIL" MODIFY ("SERVICE_CAR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_STATUS
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS" MODIFY ("SERVICE_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS" ADD CONSTRAINT "SERVICE_STATUS_PK" PRIMARY KEY ("SERVICE_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE"  ENABLE;
  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS" MODIFY ("SERVICE_CAR_ID" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS" MODIFY ("SERVICE_STATUS_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_STATUS_TYPE
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS_TYPE" MODIFY ("SERVICE_STATUS_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS_TYPE" MODIFY ("SERVICE_STATUS_DESC" NOT NULL ENABLE);
  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS_TYPE" ADD CONSTRAINT "SERVICE_STATUS_TYPE_PK" PRIMARY KEY ("SERVICE_STATUS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MGMT_TABLESPACE"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAR
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."CAR" ADD CONSTRAINT "CAR_OWNER_FK1" FOREIGN KEY ("CAR_OWNER_ID")
	  REFERENCES "AVILCHENKO"."CAR_OWNER" ("CAR_OWNER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_CAR
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."SERVICE_CAR" ADD CONSTRAINT "CAR_FK1" FOREIGN KEY ("CAR_ID")
	  REFERENCES "AVILCHENKO"."CAR" ("CAR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_DETAIL
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."SERVICE_DETAIL" ADD CONSTRAINT "SERVICE_CAR_DETAIL_FK1" FOREIGN KEY ("SERVICE_CAR_ID")
	  REFERENCES "AVILCHENKO"."SERVICE_CAR" ("SERVICE_CAR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_STATUS
--------------------------------------------------------

  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS" ADD CONSTRAINT "SERVICE_CAR_FK1" FOREIGN KEY ("SERVICE_CAR_ID")
	  REFERENCES "AVILCHENKO"."SERVICE_CAR" ("SERVICE_CAR_ID") ENABLE;
  ALTER TABLE "AVILCHENKO"."SERVICE_STATUS" ADD CONSTRAINT "SERVICE_STATUS_TYPE_FK1" FOREIGN KEY ("SERVICE_STATUS_TYPE_ID")
	  REFERENCES "AVILCHENKO"."SERVICE_STATUS_TYPE" ("SERVICE_STATUS_TYPE_ID") ENABLE;
